export const stringsCatalog = {
 en:{
   currentLanguage: "EN",
   mainTitle01: "FORBIDDEN",
   mainTitle02: "ISLAND",
   treasuresFound:"Treasures found",
   turn:"Turn :",
   floodLevel:"Flood level",
   playerIsPlaying:"{0} {1} is playing.",
   playerCards: "Player Cards",
   floodCards: "Flood Cards",
   leap: "leap",
   discard: "discard",
   copyright: "Forbidden Island is a game created by Matt Leacock and published by Gamewright.",
   mailMessage: "Thanks for playing. Comments ?, Bugs ?",
   mailLink: "Write to me !",
   mailAdress: "mailto:info@boulezrepublic.com",
   initialisation: "... Initialisation...",
   // roles
   ro_Diver: "Diver",
   ro_Pilot: "Pilot",
   ro_Explorer: "Explorer",
   ro_Messenger: "Messenger",
   ro_Navigator: "Navigator",
   ro_Engineer: "Engineer",
   //treasures:
   tr_crystal: "Crystal",
   tr_statue: "Statue",
   tr_sceptre: "Sceptre",
   tr_cup: "Cup",
   // cards
   ca_crytal: "Crystal",
   ca_cup: "Cup",
   ca_sceptre: "Sceptre",
   ca_statue: "Statue",
   ca_helicopter: "Helicopter",
   ca_sandBag: "Sand Bag",
   ca_floodRise: "Flood",
   ca_help_helicopter: "Helicopter card : Play it whenever you want. Move one or more explorers from a tile where you want.",
   ca_help_sandBag: "Sand bag card : Play it whenever you want. Dry any tile you want.",
   //
   fullFormattedNameAndRoleDiver: "Gina the {0}diver{1}",
   fullFormattedNameAndRolePilot: "Bob the {0}pilot{1}",
   fullFormattedNameAndRoleExplorer: "Brian the {0}xxplorer{1}",
   fullFormattedNameAndRoleMessenger: "Francois the {0}messenger{1}",
   fullFormattedNameAndRoleNavigator: "Boris the {0}navigator{1}",
   fullFormattedNameAndRoleEngineer: "Natacha the {0}engineer{1}",
   //
   qualificatif_M: "the",
   qualificatif_F: "the",
   qualificatif_N: "the",
   // abilities
   ab_Engineer: "Can dry two tiles in one action.",
   ab_Navigator: "Can move another player up to two tiles for one action.",
   ab_Messenger: "Can send a card to another player for one action.",
   ab_Diver: "Can move throught immersed and drawned tiles.",
   ab_Explorer: "Can move and dry orthogonaly and diagonaly.",
   ab_Pilot: "Can fly on any tile once per turn.",
   // step Names:
   step_act1outOf3: "action 1/3",
   step_act2outOf3: "action 2/3",
   step_act3outOf3: "action 3/3",
   step_DrawPlayerCards: "draw player cards",
   step_DrawFloodCards: "draw flood cards",
   // actionsNames:
   ac_move: "Move",
   ac_dry: "Dry",
   ac_give: "Give a card",
   ac_getATreasure: "\u2B50 Get a Treasure \u2B50",
   ac_sleep: "Sleep",
   ac_sendACard: "Send a card",
   ac_moveSomeone: "Move someone",
   ac_dry2Tiles: "Dry two tiles",
   ac_moveAround: "Move around",
   ac_dryAround: "Dry around",
   ac_fly: "Fly",
   ac_MoveDive: "Move/Dive",
   // actions help texts:
   ah_move: "Move to an adjacent tile.",
   ah_dry: "Dry an adjacent tile",
   ah_give: "Give a card on a character on the same tile.",
   ah_getATreasure: "Get the treasure in this temple. You have the 4 corresponding treasure cards.",
   ah_sleep: "Skip the player's remaining actions.",
   ah_sendACard: "Send a card to any character on the map.",
   ah_moveSomeone: "Move any other character from one or two tiles.",
   ah_dry2Tiles: "Dry two adjacent tiles for one action.",
   ah_moveAround: "Move to any tile around. Orthogonally and diagonally.",
   ah_dryAround: "Dry any tile around. Orthogonally and diagonally",
   ah_fly: "Fly to any tile on the map. You cannot emboard anybody with you.",
   ah_MoveDive: "Dive through any flooded or immersed tile.",
   ah_rollback: "Cancel the previous action",
   // buttons
   btn_yes: "Yes",
   btn_no: "No",
   btn_cancel: "Cancel",
   btn_next: "Next",
   btn_give: "Give",
   btn_send: "Send",
   btn_throw: "Throw away",
   btn_use: "Use it now",
   btn_pickTwoCardsFirst: "Pick the first of two cards",
   btn_pickTwocardsSec: "Pick the second of two cards",
   btn_flood: "Flood !",
   btn_nextFlooding: "Next Flooding.. Hold your breath",
   btn_cancelTheFlight: "Cancel the flight",
   btn_evacuate: "Evacuate !",
   btn_retry: "Retry ?",
   btn_understood: "Understood",
   btn_fate: "Face your fate.",
   // opening panel
   welcomeIntro: "Hola Comrade",
   howManyAdventurers: "How many adventurers ?",
   howDifficult: "How difficult ?",
   novice: "Beginner",
   normal: "Normal",
   elite: "Elite",
   legendary: "Legendary",
   language: "Which language ?",
   letsGo: "Let's go !",
   level: "Level :",
   // messages
   welcome_msg: "Welcome on the island. Choose a first action for the first character.",
   letsDrawSomePlayerCards_msg:"Let's' draw some Player Cards",
   letsFloodSomeTiles_msg: "Let's flood {0} tiles",
   nextTurn_msg: "Next Turn ! Please {0}, Choose an action.",
   nextPlayer_msg: "Next player ! Please Choose an action ",
   chooseAnAction_msg: "Please, choose an action",
   immersionXoutofY: "<div>immersion {0} out of {1}.<br/>",
   formatTileDrawning: "<span style=\"color: #DC143C\">{0} at {1} is drawning ! </span>",
   tileDrawning: "<span style=\"color: #DC143C\">Terrain is drawning ! </span>",
   explorersCantLeaveTheIsland: "Heliport is drawned. Explorers can't leave the Island any more ! Game Over !",
   thereAreXexplorersOnIt: "<br/> There are {0} explorer(s) on it. Let's evacuate them.",
   allTheTemplesAreDrawned: "Oh my God ! all the temples for {0} are drawned. You'll never get it. GAME OVER",
   formatTileIsFlooded: "{0} at {1} is flooded !",
   tileIsFlooded: "Some terrain is flooded !",
   weNeedToEvacuateTheTile: "<br/>!!! WE NEED TO EVACUATE THE TILE !!!</div>",
   floodingsAreOver: "<br/> Floodings are over.... for now.</div>",
   chooseADestinationToEvacuate: "Now choose a destination to EVACUATE",
   nowhereHeCanGo: "Oh my God. There's nowhere he can go. {0} is drawning. Noooooooo. GAME OVER.",
   topLevelReached: "Top flood level reached. The Island is submerged. Game Over",
   firstCard_msg: 'First card : {0}.',
   secondCard_msg: 'Second card : {0}.',
   okWhatsNext: "Ok. What's next ?",
   chooseALandingDestination: "Now choose a landing destination",
   youWonMsg: "The {0} valliant exppplorers leave the island with the 4 treasures. You WON !",
   noTileToDry: "No tile to dry. Keep your Sandbag.",
   chooseATileToDry: "Now choose any tile to dry",
   nowhereToGo: "Nowhere to go. Please choose another action",
   chooseADestination: "Now choose a destination",
   noTilesToDry: "No tiles to dry. Please choose another action",
   nowChooseATileToDry: "Now choose a tile to dry",
   onlyOneTileToDry: "There's only one tile you can dry. Dry it.",
   nowChooseTwoTilesToDry: "Now choose two tiles to dry",
   noCardToGive: "No cards to give. Try something else.",
   noOtherPlayerOnYourTile: "No other player on your tile. Try something else.",
   noCardToSend: "No cards to send. Try something else.",
   thisTileIsNotATemple: "This tile is not a temple.",
   thisTreasureHasBeenFoundAlready: "This treasure has been found already.",
   notEnoughCards4Treasure: "You do not have enough {0} cards to get the treasure... you need 4 , you have {1}",
   youFoundThe4th : "You found the 4th treasure ! Now, go to the heliport and leave the Island with an Helicopter card and everybody on board !",
   youFoundThe1st : "You found your first treasure ! Go on !",
   youFoundThe2nd: "You have another treasure ! Go ! Go ! Gotta catch them all",
   youFoundThe3rd: "Another treasure ! Just one more",
   youFoundTheTreasureX: "You found the treasure {0} !!!",
   doingNothing: "Doing nothing ZZZZZZZ",
   skipTurn: "Skip turn ",
   sleep: "Sleep ZZZZZZZ ",
   unexpectedClickOnActionButton: "Unexpected Click on Action button",
   pleaseFinishYourActionFirst: "Please finish your action first.",
   heCantMoveThere: "He can't move there !",
   heCantDryThere: "He can't dry anything there !",
   nowChooseASecondOneToDry: "Now choose a second one to dry",
   cantFlyThereWithHisHCard: "He can't fly there with his H card",
   cantDryThereWithHisCard: "He can't DRY there with his card",
   helicopterRideShouldStartFromTheSameTile: "Helicopter users must start from the same tile.",
   thereIsNoOneInThisHelicopter: "There is no one in this helicopter. Choose some passangers.",
   thereAreXpeopleToEvacuate: "!!! There are {0} people left to evacuate !!!</div>",
   floodingsAreOverForNow: "<br/> Floodings are over.... for now.</div>",
   floodingsGoesOn: "Flooding Goes on </div>",
   unexpectedClickOnATile: "Unexpected Clic On a Tile",
   pleaseSelectACardToGive: "Please select a card to give.",
   pleaseSelectARecipientForTheCard: "Please select a recipient for the card.",
   xCardsPerFlood: "({0} cards per flood)",
   isPlaying: "is playing.",
   whichCardDoYouWantToGive: "Which card do you want to give",
   to: "to",
   toWhomDoYouWantToGiveIt: "To whom do you want to give it ?",
   whichCardDoYouWantToSend: "Which card do you want to send",
   toWhomDoYouWantToSendIt: "To whom do you want to send it ?",
   playerChooseALandingDestination: ", choose a landing destination.",
   doYouWantToTake: ", do you want to take ",
   withYou: " with you ?",
   selectTheGuys: "Select who will fly. You can choose several explorer from the same tile.",
   hopIn: "🚁 Take Off ! [rotor noise] 🚁",
   whoDoYouWantToMove: "Who do you want to move ?",
   andMoveHimUpToTwoTiles: "and move it up to two tiles.",
   moveThisCharacter: "Move this character",
   hasMoreThan5Card: "has more than 5 cards in Hand.",
   letsGetRidOvIt: "Let's get rid Ov it : ",
   chooseAnExplorerToMove : "Choose an explorer to move",
   found_crystal : "You found the Crystal.",
   found_statue : "You found the Statue.",
   found_cup : "You found the Cup.",
   found_sceptre : "You found the Sceptre.",
 },
 fr:{
   currentLanguage: "FR",
   mainTitle01: "L'ÎLE ",
   mainTitle02: "INTERDITE",
   treasuresFound:"Trésors trouvés",
   turn:"Tour :",
   floodLevel:"Niveau d'inondation",
   playerIsPlaying:"{0} {1} joue.",
   playerCards: "Cartes joueur",
   floodCards: "Cartes inondation",
   leap: "Pioche",
   discard: "Défausse",
   copyright: "Forbidden Island est un jeu crée par Matt Leacock et publié par Gamewright.",
   mailMessage: "Commentaires ?, bugs ?",
   mailLink: "Ecrivez moi !",
   mailAdress: "mailto:info@boulezrepublic.com",
   initialisation: "... Initialisation...",
   // roles
   ro_Diver: "Plongeuse",
   ro_Pilot: "Pilote",
   ro_Explorer: "Explorateur",
   ro_Messenger: "Messager",
   ro_Navigator: "Navigateur",
   ro_Engineer: "Ingénieure",
   //treasures:
   tr_crystal: "Cristal",
   tr_statue: "Statue",
   tr_sceptre: "Sceptre",
   tr_cup: "Coupe",
   // cards
   ca_crytal: "Cristal",
   ca_cup: "Coupe",
   ca_sceptre: "Sceptre",
   ca_statue: "Statue",
   ca_helicopter: "Hélicoptère",
   ca_sandBag: "Sac de sable",
   ca_floodRise: "Inondation",
   ca_help_helicopter: "Carte Hélicoptère : Jouez la quand vous voulez. Déplacez un ou tous les explorateurs d'une même case où vous voulez.",
   ca_help_sandBag: "Carte Sac de sable : Jouez la quand vous voulez. Asséchez une case de votre choix.",
   //
   fullFormattedNameAndRoleDiver: "Gina la {0}plongeuse{1}",
   fullFormattedNameAndRolePilot: "Bob le {0}pilote{1}",
   fullFormattedNameAndRoleExplorer: "Brian l'{0}explorateur{1}",
   fullFormattedNameAndRoleMessenger: "Francois le {0}messager{1}",
   fullFormattedNameAndRoleNavigator: "Boris le {0}navigateur{1}",
   fullFormattedNameAndRoleEngineer: "Natacha l'{0}ingénieure{1}",
   //
   qualificatif_M: "le",
   qualificatif_F: "la",
   qualificatif_N: "l'",
   // abilities
   ab_Engineer: "Peut assécher deux terrains en une action.",
   ab_Navigator: "Peut déplacer un autre aventurier jusqu'à deux cases pour une action",
   ab_Messenger: "Peut envoyer une carte à un autre aventurier.",
   ab_Diver: "Peut nager à travers les terrains inondés et immergés.",
   ab_Explorer: "Peut se déplacer et assécher diagonalement.",
   ab_Pilot: "Peut voler sur n'importe quel terrain une fois par tour.",
   // step Names:
   step_act1outOf3: "action 1/3.",
   step_act2outOf3: "action 2/3.",
   step_act3outOf3: "action 3/3.",
   step_DrawPlayerCards: "tirer des cartes joueur.",
   step_DrawFloodCards: "tirer des cartes inondation.",
   // actions:
   ac_move: "Se déplacer",
   ac_dry: "Assécher",
   ac_give: "Donner une carte",
   ac_getATreasure: "\u2B50 Trouver un trésor \u2B50",
   ac_sleep: "Se reposer",
   ac_sendACard: "Envoyer une carte",
   ac_moveSomeone: "Déplacer un autre aventurier",
   ac_dry2Tiles: "Assécher deux terrains",
   ac_moveAround: "Se déplacer",
   ac_dryAround: "Assécher",
   ac_fly: "Voler",
   ac_MoveDive: "Se déplacer/Plonger",
   // actions help texts:
   ah_move: "Se déplacer sur une case adjacente.",
   ah_dry: "Assécher une case adjacente.",
   ah_give: "Donner une carte à un autre aventurier sur la même case.",
   ah_getATreasure: "Trouver le trésor dans ce temple. Vous avez les 4 cartes trésor correspondantes.",
   ah_sleep: "Passer ses actions restantes à ne rien faire.",
   ah_sendACard: "Envoyer une de ses cartes à n'importe quel aventurier sur la carte.",
   ah_moveSomeone: "Déplacer n'importe quel autre aventurier d'une ou deux cases.",
   ah_dry2Tiles: "Assécher deux case adjacente pour une action.",
   ah_moveAround: "Se déplacer d'une case. Orthogonalement ou diagonalement.",
   ah_dryAround: "Assécher une case alentour. Orthogonalement ou diagonalement.",
   ah_fly: "S'envoler sur n'importe quelle autre case. Le pilote ne peux pas emmener d'autres aventuriers avec lui.",
   ah_MoveDive: "Se déplacer en nageant à travers n'importe quelle case inondée ou coulée.",
   ah_rollback: "Annuler l'action précédente.",
   // buttons
   btn_yes: "Oui",
   btn_no: "Non",
   btn_cancel: "Annuler",
   btn_next: "Ensuite...",
   btn_give: "Donner",
   btn_send: "Envoyer",
   btn_throw: "Jeter",
   btn_use: "Utiliser Maintenant",
   btn_pickTwoCardsFirst: "Piochez la première des deux cartes.",
   btn_pickTwocardsSec: "Piochez la seconde des deux cartes.",
   btn_flood: "Inondation !",
   btn_nextFlooding: "Inondation suivante.... retenez votre souffle",
   btn_cancelTheFlight: "Annuler le vol",
   btn_evacuate: "Evacuez !",
   btn_retry: "Recommencer ?",
   btn_understood: "Compris",
   btn_fate: "Cela devais finir ainsi.",
   // opening panel
   welcomeIntro: "Hola Camarade.",
   howManyAdventurers: "Combien d'aventuriers ?",
   howDifficult: "Quelle difficulté ?",
   novice: "Novice",
   normal: "Normal",
   elite: "Elite",
   legendary: "Légende",
   language: "Quelle langue ?",
   letsGo: "En avant !",
   level: "Niveau :",
   // msgs
   welcome_msg: "Bienvenue sur l'île. Choisissez une première action pour le premier joueur.",
   letsDrawSomePlayerCards_msg: "Tirons une carte joueur.",
   letsFloodSomeTiles_msg: "Inondons {0} terrains",
   nextTurn_msg: "Tour suivant ! {0}, choisissez une action.",
   nextPlayer_msg: "Joueur suivant ! choisissez une action.",
   chooseAnAction_msg: "Choisissez une action",
   immersionXoutofY: "<div>Inondation {0} sur {1}.<br/>",
   formatTileDrawning: "<span style=\"color: #DC143C\">{0} en {1} disparait sous les flots </span>",
   tileDrawning: "<span style=\"color: #DC143C\">un terrain disparait sous les flots </span>",
   explorersCantLeaveTheIsland: "L'Héliport est coulé, les joueurs ne peuvent plus quitter l'île. Fin de Partie !",
   thereAreXexplorersOnIt: "<br/> Il y a {0} joueur(s) dessus. Evacuation !",
   allTheTemplesAreDrawned: "Oh non ! Tous les temples pour {0} sont immergés. Vous n'aurez jamais ce trésor. Fin de Partie !",
   formatTileIsFlooded: "{0} à {1} est inondé !",
   tileIsFlooded: "un terrain est inondé !",
   weNeedToEvacuateTheTile: "<br/>!!! IL FAUT EVACUER CE TERRAIN !!!</div>",
   floodingsAreOver: "<br/> Les inondations sont terminées... pour le moment.</div>",
   chooseADestinationToEvacuate: "Maintenant, choisissez un terrain où évacuer.",
   nowhereHeCanGo: "Oh non. Il n'a nulle part où aller. {0} se noie. Noooooooon. Fin de partie !",
   topLevelReached: "Niveau d'inondation maximum atteind. L'île est submergée. Fin de partie !",
   firstCard_msg: 'Première carte: {0}.',
   secondCard_msg: 'Seconde carte : {0}.',
   okWhatsNext: "Bien. Ensuite... ",
   chooseALandingDestination: "Maintenant, choisissez un terrain où atterir.",
   youWonMsg: "Les {0} vaillants aventuriers quittent l'île avec les 4 trésors. Vous avez gagné !",
   noTileToDry: "Pas de terrain à assécher. Gardez votre carte.",
   chooseATileToDry: "Choisissez un terrain à assécher.",
   nowhereToGo: "Nulle part où aller. Choisissez une autre action.",
   chooseADestination: "Maintenant, choisissez une destination.",
   noTilesToDry: "Aucun terrain à assécher, choisissez une autre action.",
   nowChooseATileToDry: "Maintenant, choisissez un terrain à assécher.",
   onlyOneTileToDry: "Il n'y a qu'un terrain à assécher. Allez-y.",
   nowChooseTwoTilesToDry: "Maintenant, choisissez deux terrains à assécher.",
   noCardToGive: "Aucune carte à donner. Essayez autre chose.",
   noOtherPlayerOnYourTile: "Aucun autre aventurier sur votre terrain. Essayez autre chose.",
   noCardToSend: "Aucune carte à envoyer. Essayez autre chose.",
   thisTileIsNotATemple: "Il n'y a pas de temple sur ce terrain.",
   thisTreasureHasBeenFoundAlready: "Ce trésor a déjà été trouvé",
   notEnoughCards4Treasure: "Vous n'avez pas assez de carte {0} pour obtenir ce trésor... Il en faut 4, vous en avez {1}",
   youFoundThe4th : "Vous avez obtenu le 4eme trésor. Allez à l'héliport et quittez l'île avec une carte Hélicoptère. Tout le monde doit être à bord.",
   youFoundThe1st : "Vous avez trouvé votre premier trésor ! Continuez !",
   youFoundThe2nd: "Encore un trésor ! En avant, attrapez les tous !",
   youFoundThe3rd: "Encore un trésor ! Plus qu'un !",
   youFoundTheTreasureX: "Vous avez trouvé le trésor {0} !!!",
   doingNothing: "Ne rien Faire",
   skipTurn: "Passer son tour ",
   sleep: "Dormir ZZZZZZZ ",
   unexpectedClickOnActionButton: "un click sur une action n'est pas ce que l'on attend. Clique ailleurs.",
   pleaseFinishYourActionFirst: "Finissez d'abord votre action.",
   heCantMoveThere: "Il ne peut se déplacer là !",
   heCantDryThere: "On ne peux rien assécher là !",
   nowChooseASecondOneToDry: "Maintenant, choisissez en une seconde à assécher.",
   cantFlyThereWithHisHCard: "Il ne peux pas atterir là avec sa carte H.",
   cantDryThereWithHisCard: "Il ne peux pas assécher là avec sa carte.",
   helicopterRideShouldStartFromTheSameTile: "Les voyageurs héliportés doivent partir d'une même case.",
   thereIsNoOneInThisHelicopter: "Il n'y a personne dans cet hélicoptère. Choisissez des passagers.",
   thereAreXpeopleToEvacuate: "!!! Il reste {0} personnes(s) à évacuer !!!</div>",
   floodingsAreOverForNow: "<br/> Les inondations sont terminées.... Pour l'instant.</div>",
   floodingsGoesOn: "Les inondations continuent. </div>",
   unexpectedClickOnATile: "un click sur un terrain n'est pas ce que l'on attend. Clique ailleurs.",
   pleaseSelectACardToGive: "Choisissez une carte à donner",
   pleaseSelectARecipientForTheCard: "Choisissez un destinataire pour la carte.",
   xCardsPerFlood: "({0} cartes par inondation)",
   isPlaying: "joue.",
   whichCardDoYouWantToGive: "Quelle carte voulez vous donner",
   whichCardDoYouWantToSend: "Quelle carte voulez vous envoyer",
   to: "à",
   toWhomDoYouWantToGiveIt: "A qui voulez vous la donner ?",
   toWhomDoYouWantToSendIt: "A qui voulez vous l'envoyer ?",
   playerChooseALandingDestination: ", choisissez un terrain où atterrir.",
   doYouWantToTake: ", voulez vous emmener ",
   withYou: " avec vous ?",
   selectTheGuys: "Qui va voler ? Vous pouvez choisir plusieurs explorateurs partant de la même case.",
   hopIn: "🚁 Décollage ! [bruit de rotor] 🚁",
   whoDoYouWantToMove: "Qui voulez vous déplacer ?",
   andMoveHimUpToTwoTiles: "puis déplacez le jusqu'à deux cases.",
   moveThisCharacter: "Déplacer",
   hasMoreThan5Card: " a plus de 5 cartes en main.",
   letsGetRidOvIt: "Il faut s'en débarasser : ",
   chooseAnExplorerToMove : "Choisissez un aventurier à déplacer.",
   found_crystal : "Vous avez découvert le Cristal.",
   found_statue : "Vous avez découvert la Statue.",
   found_cup : "Vous avez découvert la Coupe.",
   found_sceptre : "Vous avez découvert le Sceptre.",
 }
}
