export const str = {
 en:{
   currentLanguage: "EN",
   treasuresFound:"Treasures found",
   turn:"Turn :",
   floodLevel:"Flood level",
   playerIsPlaying:"{0} {1} is playing.",
   // roles
   roleStringDiver: "Diver",
   roleStringPilot: "Pilot",
   roleStringExplorer: "Explorer",
   roleStringMessenger: "Messenger",
   roleStringNavigator: "Navigator",
   roleStringEngineer: "Engineer",
   sustentif_M: "the",
   sustentif_F: "the",
   sustentif_N: "the",
   // messages
   welcome_msg: "Welcome new Player. Choose a first action for the first character.",
   letsDrawSomePlayerCards_msg:"Let's' draw some Player Cards",
   letsFloodSomeTiles_msg: "Let\'s flood {0} tiles",
   nextTurn_msg: "Next Turn ! Please {0}, Choose an action.",
   nextPlayer_msg: "Next player ! Please Choose an action ",
   chooseAnAction_msg: "Choose an action ",
   immersionXoutofY: "<div>immersion {0} out of {1}.<br/>",
   tileDrawning: "<span style=\"color: #DC143C\">{0} at {1} is drawning ! </span>",
   explorersCantLeaveTheIsland: "<br/> Heliport is drawned. Explorers can't leave the Island any more ! Game Over !",
   thereAreXexplorersOnIt: "<br/> There are {0} explorer(s) on it. Let's evacuate them.",
   allTheTemplesAreDrawned: "<br/>Oh my God ! all the temples for {0} are drawned. You'll never get it. GAME OVER",
   tileIsFlooded: "{0} at {1} is flooded !",
   weNeedToEvacuateTheTile: "<br/>!!! WE NEED TO EVACUATE THE TILE !!!</div>",
   floodingsAreOver: "<br/> Floodings are over.... for now.</div>",
   chooseADestinationToEvacuate: "Now choose a destination to EVACUATE",
   nowhereHeCanGo: "Oh my God. There's nowhere he can go. {0} is drawning. Noooooooo. GAME OVER.",
 },
 fr:{
   currentLanguage: "FR",
   treasuresFound:"Trésors trouvés",
   turn:"Tour :",
   floodLevel:"Niveau d'innondation",
   playerIsPlaying:"{0} {1} joue.",
   // roles
   roleStringDiver: "Plongeuse",
   roleStringPilot: "Pilote",
   roleStringExplorer: "Explorateur",
   roleStringMessenger: "Messager",
   roleStringNavigator: "Navigateur",
   roleStringEngineer: "Ingénieur",
   sustentif_M: "le",
   sustentif_F: "la",
   sustentif_N: "l'",
   welcome_msg: "Bienvenue sur l'île. Choisissez une première action pour le premier joueur.",
   letsDrawSomePlayerCards_msg: "Tirons une carte joueur.",
   letsFloodSomeTiles_msg: "Inondons {0} terrains",
   nextTurn_msg: "Tour suivant ! {0}, choisis une action.",
   nextPlayer_msg: "Joueur suivant ! Choisis une action.",
   chooseAnAction_msg: "Choisis une action",
   immersionXoutofY: "<div>Inondation {0} sur {1}.<br/>",
   tileDrawning: "<span style=\"color: #DC143C\">{0} en {1} disparait sous les flots </span>",
   explorersCantLeaveTheIsland: "<br/> L'Héliport est coulé, les joueurs ne peuvet plus quitter l'île. Fin de Partie !",
   thereAreXexplorersOnIt: "<br/> Il y a {0} joueur(s) dessus. Evacuation !",
   allTheTemplesAreDrawned: "<br/>Oh non ! Tous les temples pour {0} sont immergés. Vous n'aurez jamais ce trésor. Fin de Partie !",
   tileIsFlooded: "{0} à {1} est inondé !",
   weNeedToEvacuateTheTile: "<br/>!!! IL FAUT EVACUER CE TERRAIN !!!</div>",
   floodingsAreOver: "<br/> Les inondations sont terminées... pour le moment.</div>",
   chooseADestinationToEvacuate: "Maintenant, choisissez un terrain où évacuer.",
   nowhereHeCanGo: "Oh non. Il n'a nulle part où aller. {0} se noie. Noooooooon. Fin de partie.",
 }
}
