export const str = {
 en:{
   currentLanguage: "EN",
   mainTitle01: "FORBIDDEN",
   mainTitle02: "ISLAND",
   treasuresFound:"Treasures found",
   turn:"Turn :",
   floodLevel:"Flood level",
   playerIsPlaying:"{0} {1} is playing.",
   // roles
   roleStringDiver: "Diver",
   roleStringPilot: "Pilot",
   roleStringExplorer: "Explorer",
   roleStringMessenger: "Messenger",
   roleStringNavigator: "Navigator",
   roleStringEngineer: "Engineer",
   sustentif_M: "the",
   sustentif_F: "the",
   sustentif_N: "the",
   // messages
   welcome_msg: "Welcome new Player. Choose a first action for the first character.",
   letsDrawSomePlayerCards_msg:"Let's' draw some Player Cards",
   letsFloodSomeTiles_msg: "Let\'s flood {0} tiles",
   nextTurn_msg: "Next Turn ! Please {0}, Choose an action.",
   nextPlayer_msg: "Next player ! Please Choose an action ",
   chooseAnAction_msg: "Choose an action ",
   immersionXoutofY: "<div>immersion {0} out of {1}.<br/>",
   tileDrawning: "<span style=\"color: #DC143C\">{0} at {1} is drawning ! </span>",
   explorersCantLeaveTheIsland: "<br/> Heliport is drawned. Explorers can't leave the Island any more ! Game Over !",
   thereAreXexplorersOnIt: "<br/> There are {0} explorer(s) on it. Let's evacuate them.",
   allTheTemplesAreDrawned: "<br/>Oh my God ! all the temples for {0} are drawned. You'll never get it. GAME OVER",
   tileIsFlooded: "{0} at {1} is flooded !",
   weNeedToEvacuateTheTile: "<br/>!!! WE NEED TO EVACUATE THE TILE !!!</div>",
   floodingsAreOver: "<br/> Floodings are over.... for now.</div>",
   chooseADestinationToEvacuate: "Now choose a destination to EVACUATE",
   nowhereHeCanGo: "Oh my God. There's nowhere he can go. {0} is drawning. Noooooooo. GAME OVER.",
   topLevelReached: "Top flood level reached. The Island is submerged. Game Over",
   firstCard_msg: 'First card : {0}.',
   secondCard_msg: 'Second card : {0}.',
   okWhatsNext: "Ok. What's next ?",
   chooseALandingDestination: "Now choose a landing destination",
   youWonMsg: "The {0} valliant exppplorers leave the island with the 4 treasures. You WON !",
   noTileToDry: "No tile to dry. Keep your Sandbag.",
   chooseATileToDry: "Now choose any tile to dry",
   nowhereToGo: "Nowhere to go. Please choose another action",
   chooseADestination: "Now choose a destination",
   chooseALandingDestination: "Now choose a landing destination",
   noTilesToDry: "No tiles to dry. Please choose another action",
   nowChooseATileToDry: "Now choose a tile to dry",
   onlyOneTileToDry: "There's only one tile you can dry. Dry it.",
   nowChooseTwoTilesToDry: "Now choose two tiles to dry",
   noCardToGive: "No cards to give. Try something else.",
   noOtherPlayerOnYourTile: "No other player on your tile. Try something else.",
   noCardToSend: "No cards to send. Try something else.",
   thisTileIsNotATemple: "This tile is not a temple.",
   thisTreasureHasBeenFoundAlready: "This treasure has been found already.",
   notEnoughCards4Treasure: "You do not have enough {0} cards to get the treasure... you need 4 , you have {1}",
   youFoundThe4th : "You found the 4th treasure ! Now, go to the heliport and leave the Island with an Helicopter card and everybody on board !",
   youFoundThe1st : "You found your first treasure ! Go on !",
   youFoundAnotherTreasure: "You have another treasure ! Go ! Go ! Gotta catch them all",
   youFoundTheTreasureX: "You found the treasure {0} !!!",
   doingNothing: "Doing nothing ZZZZZZZ",
   skipTurn: "Skip turn ",
   sleep: "Sleep ZZZZZZZ ",
   unexpectedClickOnActionButton: "Unexpected Click on Action button",
   pleaseFinishYourActionFirst: "Please finish your action first.",
   heCantMoveThere: "He can't move there !",
   heCantDryThere: "He can't dry anything there !",
   nowChooseASecondOneToDry: "Now choose a second one to dry",
   cantFlyThereWithHisHCard: "He can't fly there with his H card",
   cantDryThereWithHisCard: "He can't DRY there with his card",
   thereAreXpeopleToEvacuate: "!!! There are {0} people left to evacuate !!!</div>",
   floodingsAreOverForNow: "<br/> Floodings are over.... for now.</div>",
   floodingsGoesOn: "Flooding Goes on </div>",
   unexpectedClickOnATile: "Unexpected Clic On a Tile",
   pleaseSelectACardToGive: "Please select a card to give.",
   pleaseSelectARecipientForTheCard: "Please select a recipient for the card.",
   xCardsPerFlood: "({0} cards per flood)",
 },
 fr:{
   currentLanguage: "FR",
   mainTitle01: "L'ÎLE",
   mainTitle02: "INTERDITE",
   treasuresFound:"Trésors trouvés",
   turn:"Tour :",
   floodLevel:"Niveau d'innondation",
   playerIsPlaying:"{0} {1} joue.",
   // roles
   roleStringDiver: "Plongeuse",
   roleStringPilot: "Pilote",
   roleStringExplorer: "Explorateur",
   roleStringMessenger: "Messager",
   roleStringNavigator: "Navigateur",
   roleStringEngineer: "Ingénieur",
   sustentif_M: "le",
   sustentif_F: "la",
   sustentif_N: "l'",
   // msgs
   welcome_msg: "Bienvenue sur l'île. Choisissez une première action pour le premier joueur.",
   letsDrawSomePlayerCards_msg: "Tirons une carte joueur.",
   letsFloodSomeTiles_msg: "Inondons {0} terrains",
   nextTurn_msg: "Tour suivant ! {0}, choisis une action.",
   nextPlayer_msg: "Joueur suivant ! Choisis une action.",
   chooseAnAction_msg: "Choisis une action",
   immersionXoutofY: "<div>Inondation {0} sur {1}.<br/>",
   tileDrawning: "<span style=\"color: #DC143C\">{0} en {1} disparait sous les flots </span>",
   explorersCantLeaveTheIsland: "<br/> L'Héliport est coulé, les joueurs ne peuvet plus quitter l'île. Fin de Partie !",
   thereAreXexplorersOnIt: "<br/> Il y a {0} joueur(s) dessus. Evacuation !",
   allTheTemplesAreDrawned: "<br/>Oh non ! Tous les temples pour {0} sont immergés. Vous n'aurez jamais ce trésor. Fin de Partie !",
   tileIsFlooded: "{0} à {1} est inondé !",
   weNeedToEvacuateTheTile: "<br/>!!! IL FAUT EVACUER CE TERRAIN !!!</div>",
   floodingsAreOver: "<br/> Les inondations sont terminées... pour le moment.</div>",
   chooseADestinationToEvacuate: "Maintenant, choisissez un terrain où évacuer.",
   nowhereHeCanGo: "Oh non. Il n'a nulle part où aller. {0} se noie. Noooooooon. Fin de partie !",
   topLevelReached: "Niveau d'innondation maximum atteind. L'île est submergée. Fin de partie !",
   firstCard_msg: 'Première carte: {0}.',
   secondCard_msg: 'Seconde carte : {0}.',
   okWhatsNext: "Bien. Ensuite... ",
   chooseALandingDestination: "Maintenant, choisissez où atterir.",
   youWonMsg: "Les {0} vaillants aventuriers quittent l'île avec les 4 trésors. Vous avez gagné !",
   noTileToDry: "Pas de terrain à assécher. Gardez votre carte.",
   chooseATileToDry: "Choisissez un terrain à assécher.",
   nowhereToGo: "Nulle part où aller. Choisissez une autre action.",
   chooseADestination: "Maintenant, choisissez une destination.",
   chooseALandingDestination: "Maintenant, choisissez un terrain où atterir.",
   noTilesToDry: "Aucun terrain à assécher, choisissez une autre action.",
   nowChooseATileToDry: "Maintenant, choisissez un terrain à assécher.",
   onlyOneTileToDry: "Il n'y a qu'un terrain à assécher. Allez-y.",
   nowChooseTwoTilesToDry: "Maintenant, choisissez deux terrains à assécher.",
   noCardToGive: "Aucune carte à donner. Essayez autre chose.",
   noOtherPlayerOnYourTile: "Aucun autre aventurier sur votre terrain. Essayez autre chose.",
   noCardToSend: "Aucune carte à envoyer. Essayez autre chose.",
   thisTileIsNotATemple: "Il n'y a pas de temple sur ce terrain.",
   thisTreasureHasBeenFoundAlready: "Ce trésor a déjà été trouvé",
   notEnoughCards4Treasure: "Vous n'avez pas assez de carte {0} pour obtenir ce trésor... Il en faut 4, vous en avez {1}",
   youFoundThe4th : "Vous avez obtenu le 4eme trésor. Allez à l'héliport et quittez l'île avec une carte Hélicoptère. Tout le monde doit être à bord.",
   youFoundThe1st : "Vous avez trouvé votre premier trésor ! Continuez !",
   youFoundAnotherTreasure: "Encore un trésor ! En avant, attrapez les tous !",
   youFoundTheTreasureX: "Vous avez trouvé le trésor {0} !!!",
   doingNothing: "Ne rien Faire",
   skipTurn: "Passer son tour ",
   sleep: "Dormir ZZZZZZZ ",
   unexpectedClickOnActionButton: "un click sur une action n'est pas ce que l'on attend. Clique ailleurs.",
   pleaseFinishYourActionFirst: "Finissez d'abord votre action.",
   heCantMoveThere: "Il ne peut se déplacer là !",
   heCantDryThere: "On ne peux rien assécher là !",
   nowChooseASecondOneToDry: "Maintenant, choisissez en une seconde à assécher.",
   cantFlyThereWithHisHCard: "Il ne peux pas atterir là avec sa carte H.",
   cantDryThereWithHisCard: "Il ne peux pas assécher là avec sa carte.",
   thereAreXpeopleToEvacuate: "!!! Il reste {0} personnes(s) à évacuer !!!</div>",
   floodingsAreOverForNow: "<br/> Les inondations sont terminées.... Pour l'instant.</div>",
   floodingsGoesOn: "Les inondations continuent. </div>",
   unexpectedClickOnATile: "un click sur un terrain n'est pas ce que l'on attend. Clique ailleurs.",
   pleaseSelectACardToGive: "Choisissez une carte à donner",
   pleaseSelectARecipientForTheCard: "Choisissez un destinataire pour la carte.",
   xCardsPerFlood: "({0} carte par inondations)",
 }
}
